### ISSUE TITLE
Deploy a static version of the storybook

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-react-components#8]
Maybe using https://github.com/storybooks/storybook-deployer and now.sh/github pages we could have a static version of the storybook up on the interwebs

**Comment by mattgrill** [comment]
Could be really useful to have everything auto-generated when master is updated. Maybe also publish the npm module?

**Comment by dawehner** [comment]
I wonder whether we can automatically publish to npm when one tags a new git version

**Comment by mattgrill** [comment]
Is that something that circle-ci supports? I've never used it.

**Comment by dawehner** [comment]
Seems so: https://circleci.com/docs/1.0/configuration/#tags I haven't used it either yet

**Comment by dawehner** [comment]
I think its good as it is?

**Comment by mattgrill** [comment]
Yep. Looks like we closed this. :)
